In [50]:
# importation de packages 
import numpy as np 
from sklearn.datasets import make_regression
from scipy.linalg import eig

In [10]:
# chargement du jeud de donnée 
data = make_regression(n_samples=1000, n_features=100)[0]

array([[ 0.38636037,  0.74194179,  1.98773966, ...,  0.68953539,
        -1.17377166, -1.53973157],
       [-0.30512997,  2.19884755,  1.47057182, ..., -0.81588756,
        -0.40676133, -0.77689975],
       [-0.30472627, -1.31429745,  0.00505987, ...,  0.65324524,
         0.00660817, -0.28916871],
       ...,
       [-0.19710344, -1.15718281, -0.35603315, ..., -0.57286094,
         1.72772354, -0.99218307],
       [ 0.67755161, -2.0317986 , -0.78920463, ...,  1.43606552,
        -0.46050141,  0.09688523],
       [-0.1608562 ,  0.55938021,  0.98531119, ...,  1.77984064,
        -0.76234097,  1.4066966 ]])

In [85]:
class ACP: 
    def __init__(self, n_comp= 2):
        """

        Args:
            n_comp (entier,  optional): donne le nombre de composante principale a choisir 
        """
        self.n_comp = n_comp 

    def fit(self, X): 
      

        # standariser les donnees 
        mean = X.mean(axis=0)
        std = X.std(axis=0)
        self.X = (X-mean) / std 

        # calculer la matrice de variance covariance 
        S = np.cov(self.X.T)

        # recuperer les valeurs propres et les vecteurs propre de la matrice de variance covariance 
        eigen_values, eigen_vectors = eig(S)

        # trier les valeurs propres 
        index = np.argsort(eigen_values)[::-1]
        self.A = eigen_vectors[index]


    def transform(self): 
        all_componement = np.dot(self.X ,self.A)
        return all_componement[:,:self.n_comp]


In [86]:
model = ACP(n_comp=3 )
model.fit(data)
model.transform( )

array([[ 0.89624478,  0.18780916, -0.52186189],
       [ 1.66532275, -1.66223695,  0.32678789],
       [ 0.49578913,  1.84708972, -1.10518178],
       ...,
       [ 0.53293002, -0.09491295, -1.06370506],
       [-0.48845187,  0.01943876, -0.41332442],
       [-1.54545037, -1.22863005,  0.33682096]])

In [59]:
A  = np.random.randint(1, 10, size=(5,3))
A 

array([[9, 7, 3],
       [4, 8, 3],
       [6, 8, 4],
       [7, 1, 4],
       [5, 8, 1]])

In [51]:
S = np.cov(A.T)

In [55]:
eigen_values, eigen_vectors = eig(S)

In [57]:
eigen_values.astype(np.float)

/var/folders/sq/462l7_3n27v2bh21r8_xxnkh0000gn/T/ipykernel_43065/2696126328.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eigen_values.astype(np.float)
/var/folders/sq/462l7_3n27v2bh21r8_xxnkh0000gn/T/ipykernel_43065/2696126328.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  eigen_values.astype(np.float)


array([11.41181463,  3.781433  ,  1.20675237])

In [66]:
index = np.argsort(eigen_values)[::-1]



In [67]:
eigen_values[index]

array([11.41181463+0.j,  3.781433  +0.j,  1.20675237+0.j])

In [68]:
eigen_vectors[index]

array([[-0.65896857, -0.67174598, -0.33840473],
       [-0.72640036,  0.68510364,  0.05454825],
       [-0.19519975, -0.2817629 ,  0.93941829]])

In [69]:
eigen_values, eigen_vectors

(array([11.41181463+0.j,  3.781433  +0.j,  1.20675237+0.j]),
 array([[-0.65896857, -0.67174598, -0.33840473],
        [-0.72640036,  0.68510364,  0.05454825],
        [-0.19519975, -0.2817629 ,  0.93941829]]))